name: officesync
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # --- CHAT SOCKET (QUAN TRỌNG NHẤT CHO CHAT) ---
  stomp_dart_client: ^1.0.0 # Không có dòng này là code Chat đỏ hết

  # --- Utilities ---
  geolocator: ^10.1.0
  network_info_plus: ^5.0.1
  permission_handler: ^11.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_secure_storage: ^9.0.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  # --- Media ---
  video_player: ^2.8.6
  chewie: ^1.8.1
  image_picker: ^1.2.1

  # --- Networking & Security ---
  dio: ^5.9.0
  bcrypt: ^1.1.3
  http: ^1.6.0 # Dùng cho API Chat

  # --- Editor & Firebase ---
  flutter_quill: 10.8.4
  speech_to_text: ^7.3.0

  # Firebase & Notification (Chỉ khai báo 1 lần ở đây)
  firebase_core: ^3.8.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^17.0.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.4
  fl_chart: ^0.66.0
  timeago: ^3.7.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# --- Cấu hình Override (Tránh xung đột version) ---
dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Cấu hình icon App
flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
