name: officesync
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  stomp_dart_client: ^1.0.0
  flutter:
    sdk: flutter

  geolocator: ^10.1.0 # Lấy GPS
  network_info_plus: ^5.0.1 # Lấy thông tin Wi-Fi (BSSID)
  permission_handler: ^11.0.1 # Quản lý quyền

  # --- UI & Utilities ---
  flutter_staggered_grid_view: ^0.7.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  intl: ^0.20.2
  google_fonts: ^6.1.0

  # --- Media ---
  video_player: ^2.8.6
  chewie: ^1.8.1
  image_picker: ^1.2.1

  # --- Networking & Security ---
  dio: ^5.9.0
  bcrypt: ^1.1.3

  # --- Editor (Cố định version) ---
  flutter_quill: 10.8.4
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# --- Cấu hình Override (Quan trọng) ---
dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

  # ✅ THÊM 3 CÁI NÀY:
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0 # Để hiện thông báo khi đang mở app
